# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
    - name: Get previous tag
      id: tag
      uses: WyriHaximus/github-action-get-previous-tag@v1
    - name: Prepare package
      run: |
        pip install -r .github/scripts/prepare-publish-requirements.txt
        VERSION=${{ steps.tag.outputs.tag }} python .github/scripts/prepare-publish.py
    - name: Build package
      if: ${{ !env.ACT }}
      run: python setup.py sdist bdist_wheel
    - name: Publish package
      if: ${{ !env.ACT }}
      uses: pypa/gh-action-pypi-publish@v1.6.4
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: dist/
    - name: Commit files
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add src/linktools/assets/frida.js
        git add src/linktools/assets/android-tools.json src/linktools/assets/android-tools.apk
        git commit -m "Auto commit artifacts (${{ steps.tag.outputs.tag }})"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: master
